# Introducción a  Numpy

**Autor:** Roberto Muñoz <br />
**E-mail:** <rmunoz@metricarts.com>

Uno de los módulos más importantes de Python es **[Numpy](http://www.numpy.org/)**. El origen de Numpy se debe principalmente al diseñador de software Jim Hugunin quien diseñó el módulo Numeric para dotar a Python de capacidades de cálculo similares a las de otros softwares como MATLAB. Posteriormente, mejoró Numeric incorporando nuevas funcionalidades naciendo lo que hoy conocemos como Numpy.

Numpy es el encargado de añadir toda la capacidad matemática y vectorial a Python haciendo posible operar con cualquier dato numérico o array (posteriormente veremos qué es un array). Incorpora operaciones tan básicas como la suma o la multiplicación u otras mucho más complejas como la transformada de Fourier o el álgebra lineal. Además incorpora herramientas que nos permiten incorporar código fuente de otros lenguajes de programación como C/C++ o Fortran lo que incrementa notablemente su compatibilidad e implementación.


## ¿Porqué usar Numpy?

En múltiples ocasiones necesitamos hacer operaciones numéricas sobre datos provenientes de archivos Excel o Bases de datos que contienen múltiples campos (columnas) y múltiples registros (filas).

Vimos que en Python existen las listas, tuplas y diccionarios, las cuales son de gran ayuda para almacenar y adminsitrar datos. Veamos qué sucede cuando queremos sumar los elementos almacenados en dos listas.

In [1]:
x=[1,2,3,4]
y=[5,6,7,8]
print(x+y)

[1, 2, 3, 4, 5, 6, 7, 8]


Como podemos notar, el operador + simplemente concatena las dos listas.
¿Alguien sugiere como podriamos sumar los elmentos de las dos listas, elemento por elemento?

## Cómo importar el paquete Numpy

Partimos importando el paquete numpy usando la función import. En este caso usaremos el alias np para referirnos de manera más abreviada a las clases y  métodos implementados en numpy.

In [2]:
import numpy as np
print(np.__version__)

1.13.3


## Definición de arreglos en Numpy

In [3]:
# Definir un arreglo 1D

x = np.array([1,2,3,4])
print(x)
print('type(x): ', type(x))
print('x.dtype: ', x.dtype)
print('x.size: ', x.size)
print('x.shape: ', x.shape)

[1 2 3 4]
type(x):  <class 'numpy.ndarray'>
x.dtype:  int64
x.size:  4
x.shape:  (4,)


In [4]:
# Definir un arreglo 1D como tipo de dato de punto flotante

x = np.array([1,2,3,4], dtype=np.float32)
print(x)
print('type(x): ', type(x))
print('x.dtype: ', x.dtype)
print('x.size: ', x.size)
print('x.shape: ', x.shape)

[ 1.  2.  3.  4.]
type(x):  <class 'numpy.ndarray'>
x.dtype:  float32
x.size:  4
x.shape:  (4,)


In [6]:
# Sumar los arreglos x e y
y = np.array([5,6,7,8])
print('x: ', x)
print('y: ', y)
print('Suma: ', x+y)

x:  [ 1.  2.  3.  4.]
y:  [5 6 7 8]
Suma:  [  6.   8.  10.  12.]


In [7]:
# Definir un arreglo 2D

x= np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(type(x))
print(x.size)
print(x.shape)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
8
(2, 4)


**See Figure 1 for an illustration of indexing on a 2D array.**<br />
<img src="images/numpy_indexing.png" width="400">

In [9]:
# Inicializar un arreglo 1D y otro 2D con ceros. Notar que usamos Y por X

x=np.zeros(10)
print('x: ', x)

y=np.zeros([2,4])
print('y:', y)

x:  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
y: [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [10]:
# Crear un arreglo usando valores aleatorios entre 0 y 1

x=np.random.random(100)
print(x)

[ 0.18644596  0.11978201  0.45932489  0.60218122  0.67845962  0.77170906
  0.01825457  0.43402624  0.8720491   0.36946698  0.12174092  0.16447172
  0.72765008  0.81408774  0.47911381  0.37276242  0.280329    0.84179052
  0.36446668  0.75561317  0.58464192  0.09391143  0.42719673  0.56814132
  0.36698071  0.09778505  0.79592703  0.44472448  0.13098522  0.63667042
  0.03539714  0.80490903  0.85646922  0.12886414  0.95726444  0.05520466
  0.8334231   0.76823933  0.86318634  0.08379661  0.56989208  0.55652717
  0.54033675  0.10000419  0.3130859   0.30027249  0.58526039  0.27144703
  0.7684797   0.15058883  0.50537582  0.8898797   0.63479515  0.29452624
  0.93326675  0.68074722  0.4082173   0.00390034  0.55380688  0.79312782
  0.69432483  0.65932335  0.16560557  0.10596857  0.33449932  0.4616263
  0.85194317  0.36610575  0.80438785  0.18955674  0.84313768  0.36134556
  0.84682747  0.54266355  0.42064723  0.72389733  0.86650687  0.17969603
  0.17550061  0.46003963  0.91128903  0.74745197  0.

In [11]:
# Extraer valores de un arreglo Numpy usando indices

x= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

print('\nx[0,3]: ', x[0,3])

print('\nx[:,0]: ', x[:,0])
print('\nx[0,:]: ', x[0,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

x[0,3]:  4

x[:,0]:  [1 5 9]

x[0,:]:  [1 2 3 4]


In [12]:
# Numpy permite crear máscaras fácilmente usando condiciones booleanas

mask=x>6
print(mask)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [13]:
# Extraer los valores de x que satisfacen la condición booleana. Para ello usamos la máscara

print(x[mask])

[ 7  8  9 10 11 12]


**See Figure 2 for an illustration of boolean indexing on a 2D array.**<br />
<img src="images/boolean_indexing.png" width="400">

In [14]:
# Sumar los valores de un arreglo 2D a lo largo del eje Y (columnas)

np.sum(x, axis=0)

array([15, 18, 21, 24])

In [15]:
# Sumar los valores de un arrego 2D a lo largo del eje X (filas)

np.sum(x, axis=1)

array([10, 26, 42])

In [17]:
# Crear la transpuesta de la matriz x

print(x.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## Funciones matemáticas

In [140]:
x=np.random.random(100)
print(x)
print('Mean: ', np.mean(x))
print('StdDev: ', np.std(x))

[ 0.16852557  0.82759454  0.93759721  0.07421415  0.85399033  0.83944451
  0.25900282  0.48627497  0.56235866  0.41246581  0.09896005  0.14704253
  0.81548291  0.78049575  0.31792487  0.43920356  0.73220208  0.39944968
  0.65861462  0.54794291  0.46803529  0.14599528  0.36812081  0.41239581
  0.53538923  0.90910926  0.85707638  0.94846572  0.15874429  0.92798357
  0.41309719  0.07004492  0.98632908  0.2025232   0.89298945  0.35516346
  0.50338437  0.50102249  0.6962746   0.62248414  0.09299552  0.07330075
  0.00775958  0.82813582  0.84053548  0.04052015  0.72023627  0.4663367
  0.46895887  0.59586113  0.07944606  0.77911098  0.21965164  0.33617147
  0.86488798  0.20143473  0.15293794  0.2427127   0.77599941  0.67177719
  0.37889744  0.77107805  0.01198106  0.89370284  0.18645281  0.25157948
  0.58602298  0.96914209  0.12029104  0.56623824  0.14085224  0.42975567
  0.06112192  0.4212431   0.5146792   0.99622001  0.22183457  0.80181196
  0.02091808  0.43428728  0.44167097  0.07997137  0.

In [141]:
x=np.random.randn(100)
print(x)
print('Mean: ', np.mean(x))
print('StdDev: ', np.std(x))

[ 0.18652597  1.55256971  1.14283458 -1.35914885  1.21468996 -0.4615599
 -0.28772215 -0.43918754  3.51730497 -0.11726413 -0.53531477  0.92511971
 -1.13513868 -0.75701252  2.46231794 -0.67093379 -0.59329276  0.11307838
  1.84918723 -0.35901512  1.1781521   0.93129658  0.39098745 -0.70786513
  0.36882945  0.1228113  -1.20879409  1.05315516  0.33192098 -0.06635965
  0.31379955  0.77870529  1.05223656 -2.48163903 -0.1372486   0.40161139
 -0.25653979  1.07119289  1.0913657   1.02538293 -1.02598548 -1.99115923
  0.51534132  0.68832854  0.71679205  0.10138614 -1.36732822  0.55832126
 -1.20533372  0.37914936 -2.88310559 -0.7302587   0.16269835 -0.44063943
 -0.20150943 -0.1316026  -1.39300834  0.35909068 -0.78927575 -0.5462339
  0.31067815 -1.16837954  0.10088436  0.08102672 -0.80075645 -0.20105449
 -0.49678653 -1.12840697  1.73212738  0.73188236 -1.70208828 -1.65167087
 -2.09354782  0.05051982  1.16470419  0.22498895 -0.15133103 -0.65246578
  1.03371634  1.59368135 -0.84576994  0.19385223  0.7

In [20]:
# Crear un arreglo de enteros que comience en 0 y termine en 10 (no incluído)

x=np.arange(0,10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
# Crear un arreglo de punto flotante que comience en 0 y termine en 10, con paso de 0.5

x=np.arange(0,10,0.5)
print(x)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5]


In [27]:
# Usar funciones trigonométricas

y=np.sin(x*np.pi)
print(y)

[  0.00000000e+00   1.00000000e+00   1.22464680e-16  -1.00000000e+00
  -2.44929360e-16   1.00000000e+00   3.67394040e-16  -1.00000000e+00
  -4.89858720e-16   1.00000000e+00   6.12323400e-16  -1.00000000e+00
  -7.34788079e-16   1.00000000e+00   8.57252759e-16  -1.00000000e+00
  -9.79717439e-16   1.00000000e+00   1.10218212e-15  -1.00000000e+00]


In [28]:
# Usar funciones como potencia

y=np.power(x,2) # elevar cada elemento del arreglo x, a la segunda potencia
print(y)

[  0.     0.25   1.     2.25   4.     6.25   9.    12.25  16.    20.25  25.
  30.25  36.    42.25  49.    56.25  64.    72.25  81.    90.25]


In [30]:
# Usar funciones como raíz cuadrada

y=np.sqrt(x) # raíz de a, del inglés "square root"
print(y)

[ 0.          0.70710678  1.          1.22474487  1.41421356  1.58113883
  1.73205081  1.87082869  2.          2.12132034  2.23606798  2.34520788
  2.44948974  2.54950976  2.64575131  2.73861279  2.82842712  2.91547595
  3.          3.082207  ]


Escribir *np.sqrt(x)* es mucho más breve que la alternativa de usar funciones nativas de Python: Calcular una a una las raíces cuadradas de cada elemento de *x*.

In [32]:
result = []
for el in x:
    result.append(el**0.5)

print("\nUsando Python built-in: ", result)
print("\nUsando Numpy: ", y)


Usando Python built-in:  [0.0, 0.70710678118654757, 1.0, 1.2247448713915889, 1.4142135623730951, 1.5811388300841898, 1.7320508075688772, 1.8708286933869707, 2.0, 2.1213203435596424, 2.2360679774997898, 2.3452078799117149, 2.4494897427831779, 2.5495097567963922, 2.6457513110645907, 2.7386127875258306, 2.8284271247461903, 2.9154759474226504, 3.0, 3.082207001484488]

Usando Numpy:  [ 0.          0.70710678  1.          1.22474487  1.41421356  1.58113883
  1.73205081  1.87082869  2.          2.12132034  2.23606798  2.34520788
  2.44948974  2.54950976  2.64575131  2.73861279  2.82842712  2.91547595
  3.          3.082207  ]
